# Generated by Django 3.0 on 2019-12-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=256)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
