# Generated by Django 3.0 on 2019-12-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191213_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
