# Generated by Django 3.0 on 2019-12-26 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_album_albumimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=70),
        ),
    ]
