# Generated by Django 3.0 on 2019-12-30 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_album_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='albums')),
            ],
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='album',
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 12, 30, 14, 0, 3, 577616, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='AlbumImage',
        ),
        migrations.AddField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api.Event'),
        ),
    ]
